#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Bababooey.Resource", IsApplication=true)]

namespace Bababooey
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int adSize = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int adSizes = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int adUnitId = 2130771970;
			
			// aapt resource value: 0x7f01000a
			public const int font = 2130771978;
			
			// aapt resource value: 0x7f010003
			public const int fontProviderAuthority = 2130771971;
			
			// aapt resource value: 0x7f010006
			public const int fontProviderCerts = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int fontProviderFetchStrategy = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int fontProviderFetchTimeout = 2130771976;
			
			// aapt resource value: 0x7f010004
			public const int fontProviderPackage = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int fontProviderQuery = 2130771973;
			
			// aapt resource value: 0x7f010009
			public const int fontStyle = 2130771977;
			
			// aapt resource value: 0x7f01000b
			public const int fontWeight = 2130771979;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f090000
			public const int abc_action_bar_embed_tabs = 2131296256;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f080008
			public const int AccentColor = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int OtherColor1 = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int OtherColor2 = 2131230730;
			
			// aapt resource value: 0x7f080007
			public const int PrimColor = 2131230727;
			
			// aapt resource value: 0x7f0800c2
			public const int md_amber_100 = 2131230914;
			
			// aapt resource value: 0x7f0800c3
			public const int md_amber_200 = 2131230915;
			
			// aapt resource value: 0x7f0800c4
			public const int md_amber_300 = 2131230916;
			
			// aapt resource value: 0x7f0800c5
			public const int md_amber_400 = 2131230917;
			
			// aapt resource value: 0x7f0800c1
			public const int md_amber_50 = 2131230913;
			
			// aapt resource value: 0x7f0800c6
			public const int md_amber_500 = 2131230918;
			
			// aapt resource value: 0x7f0800c7
			public const int md_amber_600 = 2131230919;
			
			// aapt resource value: 0x7f0800c8
			public const int md_amber_700 = 2131230920;
			
			// aapt resource value: 0x7f0800c9
			public const int md_amber_800 = 2131230921;
			
			// aapt resource value: 0x7f0800ca
			public const int md_amber_900 = 2131230922;
			
			// aapt resource value: 0x7f0800cb
			public const int md_amber_A100 = 2131230923;
			
			// aapt resource value: 0x7f0800cc
			public const int md_amber_A200 = 2131230924;
			
			// aapt resource value: 0x7f0800cd
			public const int md_amber_A400 = 2131230925;
			
			// aapt resource value: 0x7f0800ce
			public const int md_amber_A700 = 2131230926;
			
			// aapt resource value: 0x7f0800ff
			public const int md_black_1000 = 2131230975;
			
			// aapt resource value: 0x7f080052
			public const int md_blue_100 = 2131230802;
			
			// aapt resource value: 0x7f080053
			public const int md_blue_200 = 2131230803;
			
			// aapt resource value: 0x7f080054
			public const int md_blue_300 = 2131230804;
			
			// aapt resource value: 0x7f080055
			public const int md_blue_400 = 2131230805;
			
			// aapt resource value: 0x7f080051
			public const int md_blue_50 = 2131230801;
			
			// aapt resource value: 0x7f080056
			public const int md_blue_500 = 2131230806;
			
			// aapt resource value: 0x7f080057
			public const int md_blue_600 = 2131230807;
			
			// aapt resource value: 0x7f080058
			public const int md_blue_700 = 2131230808;
			
			// aapt resource value: 0x7f080059
			public const int md_blue_800 = 2131230809;
			
			// aapt resource value: 0x7f08005a
			public const int md_blue_900 = 2131230810;
			
			// aapt resource value: 0x7f08005b
			public const int md_blue_A100 = 2131230811;
			
			// aapt resource value: 0x7f08005c
			public const int md_blue_A200 = 2131230812;
			
			// aapt resource value: 0x7f08005d
			public const int md_blue_A400 = 2131230813;
			
			// aapt resource value: 0x7f08005e
			public const int md_blue_A700 = 2131230814;
			
			// aapt resource value: 0x7f080102
			public const int md_blue_grey_100 = 2131230978;
			
			// aapt resource value: 0x7f080103
			public const int md_blue_grey_200 = 2131230979;
			
			// aapt resource value: 0x7f080104
			public const int md_blue_grey_300 = 2131230980;
			
			// aapt resource value: 0x7f080105
			public const int md_blue_grey_400 = 2131230981;
			
			// aapt resource value: 0x7f080101
			public const int md_blue_grey_50 = 2131230977;
			
			// aapt resource value: 0x7f080106
			public const int md_blue_grey_500 = 2131230982;
			
			// aapt resource value: 0x7f080107
			public const int md_blue_grey_600 = 2131230983;
			
			// aapt resource value: 0x7f080108
			public const int md_blue_grey_700 = 2131230984;
			
			// aapt resource value: 0x7f080109
			public const int md_blue_grey_800 = 2131230985;
			
			// aapt resource value: 0x7f08010a
			public const int md_blue_grey_900 = 2131230986;
			
			// aapt resource value: 0x7f0800ec
			public const int md_brown_100 = 2131230956;
			
			// aapt resource value: 0x7f0800ed
			public const int md_brown_200 = 2131230957;
			
			// aapt resource value: 0x7f0800ee
			public const int md_brown_300 = 2131230958;
			
			// aapt resource value: 0x7f0800ef
			public const int md_brown_400 = 2131230959;
			
			// aapt resource value: 0x7f0800eb
			public const int md_brown_50 = 2131230955;
			
			// aapt resource value: 0x7f0800f0
			public const int md_brown_500 = 2131230960;
			
			// aapt resource value: 0x7f0800f1
			public const int md_brown_600 = 2131230961;
			
			// aapt resource value: 0x7f0800f2
			public const int md_brown_700 = 2131230962;
			
			// aapt resource value: 0x7f0800f3
			public const int md_brown_800 = 2131230963;
			
			// aapt resource value: 0x7f0800f4
			public const int md_brown_900 = 2131230964;
			
			// aapt resource value: 0x7f08006e
			public const int md_cyan_100 = 2131230830;
			
			// aapt resource value: 0x7f08006f
			public const int md_cyan_200 = 2131230831;
			
			// aapt resource value: 0x7f080070
			public const int md_cyan_300 = 2131230832;
			
			// aapt resource value: 0x7f080071
			public const int md_cyan_400 = 2131230833;
			
			// aapt resource value: 0x7f08006d
			public const int md_cyan_50 = 2131230829;
			
			// aapt resource value: 0x7f080072
			public const int md_cyan_500 = 2131230834;
			
			// aapt resource value: 0x7f080073
			public const int md_cyan_600 = 2131230835;
			
			// aapt resource value: 0x7f080074
			public const int md_cyan_700 = 2131230836;
			
			// aapt resource value: 0x7f080075
			public const int md_cyan_800 = 2131230837;
			
			// aapt resource value: 0x7f080076
			public const int md_cyan_900 = 2131230838;
			
			// aapt resource value: 0x7f080077
			public const int md_cyan_A100 = 2131230839;
			
			// aapt resource value: 0x7f080078
			public const int md_cyan_A200 = 2131230840;
			
			// aapt resource value: 0x7f080079
			public const int md_cyan_A400 = 2131230841;
			
			// aapt resource value: 0x7f08007a
			public const int md_cyan_A700 = 2131230842;
			
			// aapt resource value: 0x7f0800de
			public const int md_deep_orange_100 = 2131230942;
			
			// aapt resource value: 0x7f0800df
			public const int md_deep_orange_200 = 2131230943;
			
			// aapt resource value: 0x7f0800e0
			public const int md_deep_orange_300 = 2131230944;
			
			// aapt resource value: 0x7f0800e1
			public const int md_deep_orange_400 = 2131230945;
			
			// aapt resource value: 0x7f0800dd
			public const int md_deep_orange_50 = 2131230941;
			
			// aapt resource value: 0x7f0800e2
			public const int md_deep_orange_500 = 2131230946;
			
			// aapt resource value: 0x7f0800e3
			public const int md_deep_orange_600 = 2131230947;
			
			// aapt resource value: 0x7f0800e4
			public const int md_deep_orange_700 = 2131230948;
			
			// aapt resource value: 0x7f0800e5
			public const int md_deep_orange_800 = 2131230949;
			
			// aapt resource value: 0x7f0800e6
			public const int md_deep_orange_900 = 2131230950;
			
			// aapt resource value: 0x7f0800e7
			public const int md_deep_orange_A100 = 2131230951;
			
			// aapt resource value: 0x7f0800e8
			public const int md_deep_orange_A200 = 2131230952;
			
			// aapt resource value: 0x7f0800e9
			public const int md_deep_orange_A400 = 2131230953;
			
			// aapt resource value: 0x7f0800ea
			public const int md_deep_orange_A700 = 2131230954;
			
			// aapt resource value: 0x7f080036
			public const int md_deep_purple_100 = 2131230774;
			
			// aapt resource value: 0x7f080037
			public const int md_deep_purple_200 = 2131230775;
			
			// aapt resource value: 0x7f080038
			public const int md_deep_purple_300 = 2131230776;
			
			// aapt resource value: 0x7f080039
			public const int md_deep_purple_400 = 2131230777;
			
			// aapt resource value: 0x7f080035
			public const int md_deep_purple_50 = 2131230773;
			
			// aapt resource value: 0x7f08003a
			public const int md_deep_purple_500 = 2131230778;
			
			// aapt resource value: 0x7f08003b
			public const int md_deep_purple_600 = 2131230779;
			
			// aapt resource value: 0x7f08003c
			public const int md_deep_purple_700 = 2131230780;
			
			// aapt resource value: 0x7f08003d
			public const int md_deep_purple_800 = 2131230781;
			
			// aapt resource value: 0x7f08003e
			public const int md_deep_purple_900 = 2131230782;
			
			// aapt resource value: 0x7f08003f
			public const int md_deep_purple_A100 = 2131230783;
			
			// aapt resource value: 0x7f080040
			public const int md_deep_purple_A200 = 2131230784;
			
			// aapt resource value: 0x7f080041
			public const int md_deep_purple_A400 = 2131230785;
			
			// aapt resource value: 0x7f080042
			public const int md_deep_purple_A700 = 2131230786;
			
			// aapt resource value: 0x7f08008a
			public const int md_green_100 = 2131230858;
			
			// aapt resource value: 0x7f08008b
			public const int md_green_200 = 2131230859;
			
			// aapt resource value: 0x7f08008c
			public const int md_green_300 = 2131230860;
			
			// aapt resource value: 0x7f08008d
			public const int md_green_400 = 2131230861;
			
			// aapt resource value: 0x7f080089
			public const int md_green_50 = 2131230857;
			
			// aapt resource value: 0x7f08008e
			public const int md_green_500 = 2131230862;
			
			// aapt resource value: 0x7f08008f
			public const int md_green_600 = 2131230863;
			
			// aapt resource value: 0x7f080090
			public const int md_green_700 = 2131230864;
			
			// aapt resource value: 0x7f080091
			public const int md_green_800 = 2131230865;
			
			// aapt resource value: 0x7f080092
			public const int md_green_900 = 2131230866;
			
			// aapt resource value: 0x7f080093
			public const int md_green_A100 = 2131230867;
			
			// aapt resource value: 0x7f080094
			public const int md_green_A200 = 2131230868;
			
			// aapt resource value: 0x7f080095
			public const int md_green_A400 = 2131230869;
			
			// aapt resource value: 0x7f080096
			public const int md_green_A700 = 2131230870;
			
			// aapt resource value: 0x7f0800f6
			public const int md_grey_100 = 2131230966;
			
			// aapt resource value: 0x7f0800f7
			public const int md_grey_200 = 2131230967;
			
			// aapt resource value: 0x7f0800f8
			public const int md_grey_300 = 2131230968;
			
			// aapt resource value: 0x7f0800f9
			public const int md_grey_400 = 2131230969;
			
			// aapt resource value: 0x7f0800f5
			public const int md_grey_50 = 2131230965;
			
			// aapt resource value: 0x7f0800fa
			public const int md_grey_500 = 2131230970;
			
			// aapt resource value: 0x7f0800fb
			public const int md_grey_600 = 2131230971;
			
			// aapt resource value: 0x7f0800fc
			public const int md_grey_700 = 2131230972;
			
			// aapt resource value: 0x7f0800fd
			public const int md_grey_800 = 2131230973;
			
			// aapt resource value: 0x7f0800fe
			public const int md_grey_900 = 2131230974;
			
			// aapt resource value: 0x7f080044
			public const int md_indigo_100 = 2131230788;
			
			// aapt resource value: 0x7f080045
			public const int md_indigo_200 = 2131230789;
			
			// aapt resource value: 0x7f080046
			public const int md_indigo_300 = 2131230790;
			
			// aapt resource value: 0x7f080047
			public const int md_indigo_400 = 2131230791;
			
			// aapt resource value: 0x7f080043
			public const int md_indigo_50 = 2131230787;
			
			// aapt resource value: 0x7f080048
			public const int md_indigo_500 = 2131230792;
			
			// aapt resource value: 0x7f080049
			public const int md_indigo_600 = 2131230793;
			
			// aapt resource value: 0x7f08004a
			public const int md_indigo_700 = 2131230794;
			
			// aapt resource value: 0x7f08004b
			public const int md_indigo_800 = 2131230795;
			
			// aapt resource value: 0x7f08004c
			public const int md_indigo_900 = 2131230796;
			
			// aapt resource value: 0x7f08004d
			public const int md_indigo_A100 = 2131230797;
			
			// aapt resource value: 0x7f08004e
			public const int md_indigo_A200 = 2131230798;
			
			// aapt resource value: 0x7f08004f
			public const int md_indigo_A400 = 2131230799;
			
			// aapt resource value: 0x7f080050
			public const int md_indigo_A700 = 2131230800;
			
			// aapt resource value: 0x7f080060
			public const int md_light_blue_100 = 2131230816;
			
			// aapt resource value: 0x7f080061
			public const int md_light_blue_200 = 2131230817;
			
			// aapt resource value: 0x7f080062
			public const int md_light_blue_300 = 2131230818;
			
			// aapt resource value: 0x7f080063
			public const int md_light_blue_400 = 2131230819;
			
			// aapt resource value: 0x7f08005f
			public const int md_light_blue_50 = 2131230815;
			
			// aapt resource value: 0x7f080064
			public const int md_light_blue_500 = 2131230820;
			
			// aapt resource value: 0x7f080065
			public const int md_light_blue_600 = 2131230821;
			
			// aapt resource value: 0x7f080066
			public const int md_light_blue_700 = 2131230822;
			
			// aapt resource value: 0x7f080067
			public const int md_light_blue_800 = 2131230823;
			
			// aapt resource value: 0x7f080068
			public const int md_light_blue_900 = 2131230824;
			
			// aapt resource value: 0x7f080069
			public const int md_light_blue_A100 = 2131230825;
			
			// aapt resource value: 0x7f08006a
			public const int md_light_blue_A200 = 2131230826;
			
			// aapt resource value: 0x7f08006b
			public const int md_light_blue_A400 = 2131230827;
			
			// aapt resource value: 0x7f08006c
			public const int md_light_blue_A700 = 2131230828;
			
			// aapt resource value: 0x7f080098
			public const int md_light_green_100 = 2131230872;
			
			// aapt resource value: 0x7f080099
			public const int md_light_green_200 = 2131230873;
			
			// aapt resource value: 0x7f08009a
			public const int md_light_green_300 = 2131230874;
			
			// aapt resource value: 0x7f08009b
			public const int md_light_green_400 = 2131230875;
			
			// aapt resource value: 0x7f080097
			public const int md_light_green_50 = 2131230871;
			
			// aapt resource value: 0x7f08009c
			public const int md_light_green_500 = 2131230876;
			
			// aapt resource value: 0x7f08009d
			public const int md_light_green_600 = 2131230877;
			
			// aapt resource value: 0x7f08009e
			public const int md_light_green_700 = 2131230878;
			
			// aapt resource value: 0x7f08009f
			public const int md_light_green_800 = 2131230879;
			
			// aapt resource value: 0x7f0800a0
			public const int md_light_green_900 = 2131230880;
			
			// aapt resource value: 0x7f0800a1
			public const int md_light_green_A100 = 2131230881;
			
			// aapt resource value: 0x7f0800a2
			public const int md_light_green_A200 = 2131230882;
			
			// aapt resource value: 0x7f0800a3
			public const int md_light_green_A400 = 2131230883;
			
			// aapt resource value: 0x7f0800a4
			public const int md_light_green_A700 = 2131230884;
			
			// aapt resource value: 0x7f0800a6
			public const int md_lime_100 = 2131230886;
			
			// aapt resource value: 0x7f0800a7
			public const int md_lime_200 = 2131230887;
			
			// aapt resource value: 0x7f0800a8
			public const int md_lime_300 = 2131230888;
			
			// aapt resource value: 0x7f0800a9
			public const int md_lime_400 = 2131230889;
			
			// aapt resource value: 0x7f0800a5
			public const int md_lime_50 = 2131230885;
			
			// aapt resource value: 0x7f0800aa
			public const int md_lime_500 = 2131230890;
			
			// aapt resource value: 0x7f0800ab
			public const int md_lime_600 = 2131230891;
			
			// aapt resource value: 0x7f0800ac
			public const int md_lime_700 = 2131230892;
			
			// aapt resource value: 0x7f0800ad
			public const int md_lime_800 = 2131230893;
			
			// aapt resource value: 0x7f0800ae
			public const int md_lime_900 = 2131230894;
			
			// aapt resource value: 0x7f0800af
			public const int md_lime_A100 = 2131230895;
			
			// aapt resource value: 0x7f0800b0
			public const int md_lime_A200 = 2131230896;
			
			// aapt resource value: 0x7f0800b1
			public const int md_lime_A400 = 2131230897;
			
			// aapt resource value: 0x7f0800b2
			public const int md_lime_A700 = 2131230898;
			
			// aapt resource value: 0x7f0800d0
			public const int md_orange_100 = 2131230928;
			
			// aapt resource value: 0x7f0800d1
			public const int md_orange_200 = 2131230929;
			
			// aapt resource value: 0x7f0800d2
			public const int md_orange_300 = 2131230930;
			
			// aapt resource value: 0x7f0800d3
			public const int md_orange_400 = 2131230931;
			
			// aapt resource value: 0x7f0800cf
			public const int md_orange_50 = 2131230927;
			
			// aapt resource value: 0x7f0800d4
			public const int md_orange_500 = 2131230932;
			
			// aapt resource value: 0x7f0800d5
			public const int md_orange_600 = 2131230933;
			
			// aapt resource value: 0x7f0800d6
			public const int md_orange_700 = 2131230934;
			
			// aapt resource value: 0x7f0800d7
			public const int md_orange_800 = 2131230935;
			
			// aapt resource value: 0x7f0800d8
			public const int md_orange_900 = 2131230936;
			
			// aapt resource value: 0x7f0800d9
			public const int md_orange_A100 = 2131230937;
			
			// aapt resource value: 0x7f0800da
			public const int md_orange_A200 = 2131230938;
			
			// aapt resource value: 0x7f0800db
			public const int md_orange_A400 = 2131230939;
			
			// aapt resource value: 0x7f0800dc
			public const int md_orange_A700 = 2131230940;
			
			// aapt resource value: 0x7f08001a
			public const int md_pink_100 = 2131230746;
			
			// aapt resource value: 0x7f08001b
			public const int md_pink_200 = 2131230747;
			
			// aapt resource value: 0x7f08001c
			public const int md_pink_300 = 2131230748;
			
			// aapt resource value: 0x7f08001d
			public const int md_pink_400 = 2131230749;
			
			// aapt resource value: 0x7f080019
			public const int md_pink_50 = 2131230745;
			
			// aapt resource value: 0x7f08001e
			public const int md_pink_500 = 2131230750;
			
			// aapt resource value: 0x7f08001f
			public const int md_pink_600 = 2131230751;
			
			// aapt resource value: 0x7f080020
			public const int md_pink_700 = 2131230752;
			
			// aapt resource value: 0x7f080021
			public const int md_pink_800 = 2131230753;
			
			// aapt resource value: 0x7f080022
			public const int md_pink_900 = 2131230754;
			
			// aapt resource value: 0x7f080023
			public const int md_pink_A100 = 2131230755;
			
			// aapt resource value: 0x7f080024
			public const int md_pink_A200 = 2131230756;
			
			// aapt resource value: 0x7f080025
			public const int md_pink_A400 = 2131230757;
			
			// aapt resource value: 0x7f080026
			public const int md_pink_A700 = 2131230758;
			
			// aapt resource value: 0x7f080028
			public const int md_purple_100 = 2131230760;
			
			// aapt resource value: 0x7f080029
			public const int md_purple_200 = 2131230761;
			
			// aapt resource value: 0x7f08002a
			public const int md_purple_300 = 2131230762;
			
			// aapt resource value: 0x7f08002b
			public const int md_purple_400 = 2131230763;
			
			// aapt resource value: 0x7f080027
			public const int md_purple_50 = 2131230759;
			
			// aapt resource value: 0x7f08002c
			public const int md_purple_500 = 2131230764;
			
			// aapt resource value: 0x7f08002d
			public const int md_purple_600 = 2131230765;
			
			// aapt resource value: 0x7f08002e
			public const int md_purple_700 = 2131230766;
			
			// aapt resource value: 0x7f08002f
			public const int md_purple_800 = 2131230767;
			
			// aapt resource value: 0x7f080030
			public const int md_purple_900 = 2131230768;
			
			// aapt resource value: 0x7f080031
			public const int md_purple_A100 = 2131230769;
			
			// aapt resource value: 0x7f080032
			public const int md_purple_A200 = 2131230770;
			
			// aapt resource value: 0x7f080033
			public const int md_purple_A400 = 2131230771;
			
			// aapt resource value: 0x7f080034
			public const int md_purple_A700 = 2131230772;
			
			// aapt resource value: 0x7f08000c
			public const int md_red_100 = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int md_red_200 = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int md_red_300 = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int md_red_400 = 2131230735;
			
			// aapt resource value: 0x7f08000b
			public const int md_red_50 = 2131230731;
			
			// aapt resource value: 0x7f080010
			public const int md_red_500 = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int md_red_600 = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int md_red_700 = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int md_red_800 = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int md_red_900 = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int md_red_A100 = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int md_red_A200 = 2131230742;
			
			// aapt resource value: 0x7f080017
			public const int md_red_A400 = 2131230743;
			
			// aapt resource value: 0x7f080018
			public const int md_red_A700 = 2131230744;
			
			// aapt resource value: 0x7f08007c
			public const int md_teal_100 = 2131230844;
			
			// aapt resource value: 0x7f08007d
			public const int md_teal_200 = 2131230845;
			
			// aapt resource value: 0x7f08007e
			public const int md_teal_300 = 2131230846;
			
			// aapt resource value: 0x7f08007f
			public const int md_teal_400 = 2131230847;
			
			// aapt resource value: 0x7f08007b
			public const int md_teal_50 = 2131230843;
			
			// aapt resource value: 0x7f080080
			public const int md_teal_500 = 2131230848;
			
			// aapt resource value: 0x7f080081
			public const int md_teal_600 = 2131230849;
			
			// aapt resource value: 0x7f080082
			public const int md_teal_700 = 2131230850;
			
			// aapt resource value: 0x7f080083
			public const int md_teal_800 = 2131230851;
			
			// aapt resource value: 0x7f080084
			public const int md_teal_900 = 2131230852;
			
			// aapt resource value: 0x7f080085
			public const int md_teal_A100 = 2131230853;
			
			// aapt resource value: 0x7f080086
			public const int md_teal_A200 = 2131230854;
			
			// aapt resource value: 0x7f080087
			public const int md_teal_A400 = 2131230855;
			
			// aapt resource value: 0x7f080088
			public const int md_teal_A700 = 2131230856;
			
			// aapt resource value: 0x7f080100
			public const int md_white_1000 = 2131230976;
			
			// aapt resource value: 0x7f0800b4
			public const int md_yellow_100 = 2131230900;
			
			// aapt resource value: 0x7f0800b5
			public const int md_yellow_200 = 2131230901;
			
			// aapt resource value: 0x7f0800b6
			public const int md_yellow_300 = 2131230902;
			
			// aapt resource value: 0x7f0800b7
			public const int md_yellow_400 = 2131230903;
			
			// aapt resource value: 0x7f0800b3
			public const int md_yellow_50 = 2131230899;
			
			// aapt resource value: 0x7f0800b8
			public const int md_yellow_500 = 2131230904;
			
			// aapt resource value: 0x7f0800b9
			public const int md_yellow_600 = 2131230905;
			
			// aapt resource value: 0x7f0800ba
			public const int md_yellow_700 = 2131230906;
			
			// aapt resource value: 0x7f0800bb
			public const int md_yellow_800 = 2131230907;
			
			// aapt resource value: 0x7f0800bc
			public const int md_yellow_900 = 2131230908;
			
			// aapt resource value: 0x7f0800bd
			public const int md_yellow_A100 = 2131230909;
			
			// aapt resource value: 0x7f0800be
			public const int md_yellow_A200 = 2131230910;
			
			// aapt resource value: 0x7f0800bf
			public const int md_yellow_A400 = 2131230911;
			
			// aapt resource value: 0x7f0800c0
			public const int md_yellow_A700 = 2131230912;
			
			// aapt resource value: 0x7f080003
			public const int notification_action_color_filter = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int notification_icon_bg_color = 2131230724;
			
			// aapt resource value: 0x7f080000
			public const int notification_material_background_media_default_color = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int primary_text_default_material_dark = 2131230721;
			
			// aapt resource value: 0x7f080005
			public const int ripple_material_light = 2131230725;
			
			// aapt resource value: 0x7f080002
			public const int secondary_text_default_material_dark = 2131230722;
			
			// aapt resource value: 0x7f080006
			public const int secondary_text_default_material_light = 2131230726;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f0a0004
			public const int compat_button_inset_horizontal_material = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int compat_button_inset_vertical_material = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int compat_button_padding_horizontal_material = 2131361798;
			
			// aapt resource value: 0x7f0a0007
			public const int compat_button_padding_vertical_material = 2131361799;
			
			// aapt resource value: 0x7f0a0008
			public const int compat_control_corner_material = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public const int notification_action_icon_size = 2131361801;
			
			// aapt resource value: 0x7f0a000a
			public const int notification_action_text_size = 2131361802;
			
			// aapt resource value: 0x7f0a000b
			public const int notification_big_circle_margin = 2131361803;
			
			// aapt resource value: 0x7f0a0001
			public const int notification_content_margin_start = 2131361793;
			
			// aapt resource value: 0x7f0a000c
			public const int notification_large_icon_height = 2131361804;
			
			// aapt resource value: 0x7f0a000d
			public const int notification_large_icon_width = 2131361805;
			
			// aapt resource value: 0x7f0a0002
			public const int notification_main_column_padding_top = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int notification_media_narrow_margin = 2131361795;
			
			// aapt resource value: 0x7f0a000e
			public const int notification_right_icon_size = 2131361806;
			
			// aapt resource value: 0x7f0a0000
			public const int notification_right_side_padding_top = 2131361792;
			
			// aapt resource value: 0x7f0a000f
			public const int notification_small_icon_background_padding = 2131361807;
			
			// aapt resource value: 0x7f0a0010
			public const int notification_small_icon_size_as_large = 2131361808;
			
			// aapt resource value: 0x7f0a0011
			public const int notification_subtext_size = 2131361809;
			
			// aapt resource value: 0x7f0a0012
			public const int notification_top_pad = 2131361810;
			
			// aapt resource value: 0x7f0a0013
			public const int notification_top_pad_large_text = 2131361811;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int notification_action_background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int notification_bg = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int notification_bg_low = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int notification_bg_low_normal = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int notification_bg_low_pressed = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int notification_bg_normal = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int notification_bg_normal_pressed = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int notification_icon_background = 2130837513;
			
			// aapt resource value: 0x7f02000d
			public const int notification_template_icon_bg = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int notification_template_icon_low_bg = 2130837518;
			
			// aapt resource value: 0x7f02000a
			public const int notification_tile_bg = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int notify_panel_notification_icon_bg = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int RoundButton = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b000c
			public const int Bababooey = 2131427340;
			
			// aapt resource value: 0x7f0b000f
			public const int BababooeyCount = 2131427343;
			
			// aapt resource value: 0x7f0b000e
			public const int Bababooeys = 2131427342;
			
			// aapt resource value: 0x7f0b000b
			public const int ButtonContent = 2131427339;
			
			// aapt resource value: 0x7f0b000a
			public const int MainLayout = 2131427338;
			
			// aapt resource value: 0x7f0b000d
			public const int TextContent = 2131427341;
			
			// aapt resource value: 0x7f0b0014
			public const int action0 = 2131427348;
			
			// aapt resource value: 0x7f0b0011
			public const int action_container = 2131427345;
			
			// aapt resource value: 0x7f0b0018
			public const int action_divider = 2131427352;
			
			// aapt resource value: 0x7f0b0012
			public const int action_image = 2131427346;
			
			// aapt resource value: 0x7f0b0013
			public const int action_text = 2131427347;
			
			// aapt resource value: 0x7f0b0022
			public const int actions = 2131427362;
			
			// aapt resource value: 0x7f0b0010
			public const int adView = 2131427344;
			
			// aapt resource value: 0x7f0b0005
			public const int async = 2131427333;
			
			// aapt resource value: 0x7f0b0006
			public const int blocking = 2131427334;
			
			// aapt resource value: 0x7f0b0015
			public const int cancel_action = 2131427349;
			
			// aapt resource value: 0x7f0b001d
			public const int chronometer = 2131427357;
			
			// aapt resource value: 0x7f0b0024
			public const int end_padder = 2131427364;
			
			// aapt resource value: 0x7f0b0007
			public const int forever = 2131427335;
			
			// aapt resource value: 0x7f0b001f
			public const int icon = 2131427359;
			
			// aapt resource value: 0x7f0b0023
			public const int icon_group = 2131427363;
			
			// aapt resource value: 0x7f0b001e
			public const int info = 2131427358;
			
			// aapt resource value: 0x7f0b0008
			public const int italic = 2131427336;
			
			// aapt resource value: 0x7f0b0000
			public const int line1 = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int line3 = 2131427329;
			
			// aapt resource value: 0x7f0b0017
			public const int media_actions = 2131427351;
			
			// aapt resource value: 0x7f0b0009
			public const int normal = 2131427337;
			
			// aapt resource value: 0x7f0b0021
			public const int notification_background = 2131427361;
			
			// aapt resource value: 0x7f0b001a
			public const int notification_main_column = 2131427354;
			
			// aapt resource value: 0x7f0b0019
			public const int notification_main_column_container = 2131427353;
			
			// aapt resource value: 0x7f0b0020
			public const int right_icon = 2131427360;
			
			// aapt resource value: 0x7f0b001b
			public const int right_side = 2131427355;
			
			// aapt resource value: 0x7f0b0016
			public const int status_bar_latest_event_content = 2131427350;
			
			// aapt resource value: 0x7f0b0002
			public const int text = 2131427330;
			
			// aapt resource value: 0x7f0b0003
			public const int text2 = 2131427331;
			
			// aapt resource value: 0x7f0b001c
			public const int time = 2131427356;
			
			// aapt resource value: 0x7f0b0004
			public const int title = 2131427332;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050001
			public const int cancel_button_image_alpha = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int google_play_services_version = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int status_bar_notification_info_maxnum = 2131034114;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int notification_action = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int notification_action_tombstone = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int notification_media_action = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int notification_media_cancel_action = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int notification_template_big_media = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int notification_template_big_media_custom = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int notification_template_big_media_narrow = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int notification_template_big_media_narrow_custom = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int notification_template_custom_big = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int notification_template_icon_group = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int notification_template_lines_media = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int notification_template_media = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int notification_template_media_custom = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int notification_template_part_chronometer = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int notification_template_part_time = 2130903055;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int BABABOOEY = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060006
			public const int App_Id = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int ApplicationName = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int Bababooey = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int BababooeyCounter = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int ad_unit_id = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int common_google_play_services_unknown_issue = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int status_bar_notification_info_overflow = 2131099649;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f07000d
			public const int MaterialTheme = 2131165197;
			
			// aapt resource value: 0x7f070006
			public const int TextAppearance_Compat_Notification = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int TextAppearance_Compat_Notification_Info = 2131165191;
			
			// aapt resource value: 0x7f070001
			public const int TextAppearance_Compat_Notification_Info_Media = 2131165185;
			
			// aapt resource value: 0x7f07000c
			public const int TextAppearance_Compat_Notification_Line2 = 2131165196;
			
			// aapt resource value: 0x7f070005
			public const int TextAppearance_Compat_Notification_Line2_Media = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int TextAppearance_Compat_Notification_Media = 2131165186;
			
			// aapt resource value: 0x7f070008
			public const int TextAppearance_Compat_Notification_Time = 2131165192;
			
			// aapt resource value: 0x7f070003
			public const int TextAppearance_Compat_Notification_Time_Media = 2131165187;
			
			// aapt resource value: 0x7f070009
			public const int TextAppearance_Compat_Notification_Title = 2131165193;
			
			// aapt resource value: 0x7f070004
			public const int TextAppearance_Compat_Notification_Title_Media = 2131165188;
			
			// aapt resource value: 0x7f070000
			public const int Theme_IAPTheme = 2131165184;
			
			// aapt resource value: 0x7f07000a
			public const int Widget_Compat_NotificationActionContainer = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int Widget_Compat_NotificationActionText = 2131165195;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AdsAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 0
			public const int AdsAttrs_adSize = 0;
			
			// aapt resource value: 1
			public const int AdsAttrs_adSizes = 1;
			
			// aapt resource value: 2
			public const int AdsAttrs_adUnitId = 2;
			
			public static int[] FontFamily = new int[] {
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 1
			public const int FontFamilyFont_font = 1;
			
			// aapt resource value: 0
			public const int FontFamilyFont_fontStyle = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_fontWeight = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
